# Site settings
title: Ospek Project
SEOTitle: Blog | Ospek Project
header-img: img/home-bg.jpg
email: amek_chesster@yahoo.com.hk
description: "everyday gratitude ... programmer notes"
keyword: "silent,writer,joy,code"
url: "https://os-pek.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'

# allow future post
future: true

# seo tag
author: am k
twitter:
 username: anak_it

# facebook:
#  app_id:
#  publisher:
#  admins:

logo: /img/photo.jpg

# social:
#  name:
#  links:
#   - link1
#   - link2

# webmaster_verifications:
#  google:
#  bing:
#  alexa:
#  yandex:
#  baidu: 

lang: id_ID

# SNS settings
RSS: true
# weibo_username:     
# zhihu_username:     
github_username: os-pek
twitter_username: anak_it
# facebook_username:  

# Jekyll mentions
jekyll-mentions:
 base_url: https://twitter.com

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate,jekyll-sitemap,jekyll-seo-tag,jemoji,jekyll-mentions]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: ospek-project

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-72420661-1'            # Format: UA-xxxxxx-xx

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Sejenius apapun seseorang pasti pernah melakukan kesalahan - haruko"
sidebar-avatar: /img/photo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
      {
        title: "sergeyzhuk",
        href: "http://sergeyzhuk.me"
    },{
    title: "nikic",
    href: "http://nikic.github.io"
    },{
    title: "dustingram",
    href: "https://dustingram.com"
    }
]
